### ISSUE TITLE
Make automated semantic versioning work with new PR template

### ISSUE THREAD

**Issue by andreakreichgauer** [dot-base/.github#26]
### 🔥 Bug Description
In order to make our automated semantic versioning in github-actions work again, we need to parse the commit message in accordance with [conventional commits](conventional commits).

### Goals
So far we used the PR description as a commit message. With our new PR templates we have to parse it and just use 
- PR title (`feat: xxxx`)
- PR section ticket (`This closes #xyz.`)
- breaking change footer if applicable (`BREAKING CHANGE: some breaking change description or DELETE this line. 🚨`)

**Comment by cheyer** [comment]
This seems to work:
https://github.com/dot-base/medical-dashboard/releases/tag/v6.0.0

**Comment by andreakreichgauer** [comment]
Lesson learned: If a release contains a Breaking Change, the whole PR body is pasted to changelog as well. This was why we assumed a bug here
