### ISSUE TITLE
add chore to release  changelog 

### ISSUE THREAD

**Issue by andreakreichgauer** [dot-base/.github#29]
### 🚀 Feature Description
PRs of type 'chore' should also appear in our auto-generated changelog.

### Goals
This needs to be fixed in all repositories, that use this github actions:

- [x] fhir-resources: https://github.com/dot-base/fhir-resources/pull/446
- [x] medical-dashboard: https://github.com/dot-base/medical-dashboard/pull/1293
- [x] data-graph: https://github.com/dot-base/data-graph/pull/84
- [x] fhir-server: https://github.com/dot-base/fhir-server/pull/247
- [x] keycloak: https://github.com/dot-base/keycloak/pull/77
- [x] hdp-adapter: https://github.com/dot-base/hdp-adapter/pull/60
- [x] icd-10-api: https://github.com/dot-base/icd-10-api/pull/58
- [x] file-storage api: https://github.com/dot-base/file-storage-api/pull/53
- [x] authentication gateway: https://github.com/dot-base/authentication-gateway/pull/60
- [x] error-handler: https://github.com/dot-base/error-handler/pull/24
- [x] dotbase.org: `changelog.config.js` does not exist
- [x] app.dotbase.org: `changelog.config.js` does not exist
- [x] comm-server-adapter: `changelog.config.js` does not exist

**Comment by cheyer** [comment]
Started with Medical Dashboard, once it is merged and works, we can extend this change to other repositories.
